run:
  timeout: 2m
  skip-dirs:
    - .../../mocks
    - hack
    - testing
linters:
  enable:
    - vet
    - deadcode
    - goimports
    - varcheck
    - structcheck
    - ineffassign
    - unconvert
    - unparam
